plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}" apply false
	id 'maven-publish'
}

subprojects {
	apply plugin: 'net.fabricmc.fabric-loom'
	apply plugin: 'maven-publish'

	version = rootProject.mod_version
	group = rootProject.maven_group

	repositories {
		mavenLocal()
		mavenCentral()
	}

	dependencies {
		minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
		implementation "net.fabricmc:fabric-loader:${rootProject.loader_version}"
		implementation "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"
	}

	tasks.withType(JavaCompile).configureEach {
		it.options.release = 25
	}

	java {
		withSourcesJar()
		sourceCompatibility = JavaVersion.VERSION_25
		targetCompatibility = JavaVersion.VERSION_25
	}

	jar {
		from(rootProject.file("LICENSE")) {
			rename { "${it}-${project.name}" }
		}
	}

	processResources {
		inputs.property "version", project.version

		filesMatching("fabric.mod.json") {
			expand "version": project.version
		}
	}
}
