pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

// Should match your modid
rootProject.name = 'savs-essentials'

include 'core'
include 'mod'
include 'addons:storage-json'
include 'addons:messaging-nats'
include 'addons:nats-standalone'
