base {
    archivesName = "savs-essentials-nats-standalone"
}

loom {
    mods {
        "savs-essentials-nats-standalone" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    // Core API is required to implement the provider
    compileOnly project(":core")
    
    // NATS client - bundled into the final jar
    include(implementation("io.nats:jnats:2.25.2"))
    
    // Zstd compression
    include(implementation("com.github.luben:zstd-jni:1.5.7-1"))
}
